language: ruby
sudo: false
notifications:
  email: false
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: "d871b319ec1bda273ae52b41e7120d094082b8fc952255346168b56736abafd6"
env:
  - SECRET_KEY_BASE=3726902eb363750966ae9879eff39e77f0c7508b7e2128365fcc9c65c02d113c04dbf571cc83dbf49967b0ddb1e57cdcd88f0195652662586ce92d0601811f04
rvm:
  - 2.4.1
before_install:
  - gem update --system
  - gem install bundler
script:
  - RAILS_ENV=test bin/rails db:migrate:reset
  - bin/rspec
  - bin/rubocop --fail-level=W
after_success:
  - bin/bundle exec codeclimate-test-reporter
