---
version: "3"
services:
  ap:
    image: "supercaracal/amazon-linux-rails-app"
    depends_on:
      - "db"
    environment:
      - "REPO=https://github.com/supercaracal/japan-masters-swimming.git"
      - "BRANCH=master"
      - "RAILS_ENV=production"
      - "SECRET_KEY_BASE=${SECRET_KEY_BASE}"
      - "HOST_DB=db"
      - "PASSWORD_DB=${POSTGRES_PASSWORD}"
    ports:
      - "${PORT_AP}:80"
  db:
    build:
      context: "./docker/db"
      args:
        - "BASE_BACKUP_FILE=swim_db_basebackup_${BASE_BACKUP_DATE}.tar.gz"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "PGDATA=/var/lib/postgresql/swim"
    ports:
      - "${PORT_DB}:5432"
