default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("HOST_DB") { 'localhost' } %>
  port: <%= ENV.fetch("PORT_DB") { 5432 } %>
  username: postgres
  password: ~

development:
  <<: *default
  database: japan_masters_swimming_development

test:
  <<: *default
  database: japan_masters_swimming_test

production:
  <<: *default
  database: japan_masters_swimming
